title: Gabriel Alejandro López López (glpzzz)
email: glpz@daxslab.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I’m Gabriel Alejandro López López. I’m a software engineer living in Cienfuegos, Cuba. 
  I am a fan of programming, web development, and entrepreneurship. 
  I’m also interested in technology and music.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://glpzzz.dev"
twitter_username: glpzzz
github_username:  glpzzz

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  -
    scope:
        path: "" # an empty string here means all files in the project
    values:
        layout: "home"
  -
    scope:
        path: "" # an empty string here means all files in the project
        type: "posts" # previously `post` in Jekyll 2.2.
    values:
        is_post: true

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

markdown: kramdown
highlighter: rouge
